services:
  postgres:
    image: postgres:14-alpine
    container_name: aegira-postgres
    environment:
      POSTGRES_DB: aegira_loan
      POSTGRES_USER: aegira
      POSTGRES_PASSWORD: aegira_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U aegira -d aegira_loan"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - aegira-network

  redis:
    image: redis:5.0.3-alpine
    container_name: aegira-redis
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - aegira-network

  backend:
    build:
      context: "./aegira-loan-service (Backend)"
      dockerfile: Dockerfile
    container_name: aegira-backend
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://aegira-postgres:5432/aegira_loan
      SPRING_DATASOURCE_USERNAME: aegira
      SPRING_DATASOURCE_PASSWORD: aegira_password

      REDIS_HOST: aegira-redis
      REDIS_PORT: 6379

      JWT_SECRET: change-this-secret
      JWT_EXPIRATION: 3600000

      LOAN_DATA_SOURCE_MODE: DATABASE
      IDEMPOTENCY_ENABLED: "true"
      IDEMPOTENCY_TTL_SECONDS: "86400"
    networks:
      - aegira-network

  frontend:
    build:
      context: "./creditappdemo (Frontend)"
      dockerfile: Dockerfile
    container_name: creditappdemo-frontend
    depends_on:
      - backend
    ports:
      - "5173:5173"
    environment:
      VITE_API_URL: http://localhost:8080
    networks:
      - aegira-network
  
  runner:
      image: myoung34/github-runner:latest
      container_name: github-runner-phase4
      environment:
          REPO_URL: https://github.com/ValentinusRendy/phase4-cicd-deployment
          RUNNER_NAME: laptop-runner
          RUNNER_TOKEN: BMEV3IN6Q7FTVYS5CZUJZQTKKELEE  # ganti dengan token
          LABELS: docker-local
      volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - ./runner-data:/runner/data
      restart: unless-stopped

volumes:
  postgres_data:
  redis_data:

networks:
  aegira-network:
    driver: bridge
    