services:
  runner:
    build:
      context: .
      dockerfile: Dockerfile.runner

    container_name: github-runner-phase4

    environment:
      REPO_URL: https://github.com/ValentinusRendy/phase4-cicd-deployment
      RUNNER_NAME: laptop-runner
      RUNNER_TOKEN: BMEV3IP6WGEPAODJCVS7XCDKKEWBG
      LABELS: docker-local
      RUN_AS_ROOT: "true"

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./runner-data:/runner/data

    restart: unless-stopped