FROM myoung34/github-runner:latest

USER root

RUN apt-get update && \
    apt-get install -y \
    maven \
    git \
    curl

RUN curl -fsSL https://deb.nodesource.com/setup_22.x | bash - && \
    apt-get install -y nodejs

RUN node -v && npm -v && mvn -version