name: Pipeline Pertama

on:
  push:
    branches:
      - main

jobs:

  backend-test:
    runs-on: [self-hosted, Linux]

    defaults:
      run:
        working-directory: "./aegira-loan-service (Backend)"

    steps:
      - uses: actions/checkout@v4

      - name: Cek Java
        run: |
          java -version

      - name: Cek Maven
        run: |
          mvn -version

      - name: Backend Unit Test
        run: |
          mvn clean test

  frontend-test:
    runs-on: [self-hosted, Linux]
    needs: backend-test

    defaults:
      run:
        working-directory: "./creditappdemo (Frontend)"

    steps:
      - uses: actions/checkout@v4

      - name: Cek Node
        run: |
          node -v
          npm -v

      - name: Install Dependencies
        run: |
          npm ci

      - name: Install Playwright Browser
        run: |
          npx playwright install

      - name: Frontend Test
        run: |
          npx playwright test

  deploy:
    runs-on: [self-hosted, Linux]
    needs:
      - backend-test
      - frontend-test

    steps:
      - uses: actions/checkout@v4

      - name: Deploy aplikasi
        run: |
          docker compose up -d --build